# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ProjektCheck
                                 A QGIS plugin
 ProjektCheck
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-02-21
        copyright            : (C) 2019 by GGR
        email                : franke@ggr-planung.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import os
import sys

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ProjektCheck class from file ProjektCheck.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    # append this path to system, so that subfolders are recognized as
    # packages
    sys.path.append(os.path.dirname(os.path.abspath(__file__)))
    from .settings import settings
    from .ProjektCheck import ProjektCheck
    return ProjektCheck(iface)
